name: vynthra
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.20

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  expandable: ^5.0.1
  google_generative_ai: ^0.4.6
  mongo_dart: ^0.10.4
  flutter_expandable_fab: ^2.3.0
  get: ^4.7.2
  flutter_sticky_header: ^0.7.0
  loading_animation_widget: ^1.3.0
  flutter_widget_from_html_core: ^0.16.0
  flutter_launcher_icons: ^0.14.3
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/vynthra_logo_with_bg.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cloud
      fonts:
        - asset: assets/fonts/cloud/Cloud-Light.otf
        - asset: assets/fonts/cloud/Cloud-Bold.otf
          weight: 700