default_platform(:android)

platform :android do
  desc "Build and distribute to Firebase App Distribution"
  lane :distribute_firebase do
    # ใช้เวอร์ชันจาก environment variable
    version_number = ENV["FLUTTER_VERSION"]
    puts "Using version: #{version_number}"

    unless version_number
      UI.user_error!("FLUTTER_VERSION environment variable not set")
    end

    # สร้าง Flutter APK
    sh("cd .. && cd .. && flutter build apk --release")

    # เปลี่ยนชื่อไฟล์ APK ตาม pattern ที่ต้องการ
    default_apk_path = "../build/app/outputs/flutter-apk/app-release.apk"
    renamed_apk_path = "../build/app/outputs/flutter-apk/vynthra-#{version_number}.apk"

    # เปลี่ยนชื่อไฟล์
    sh("cp #{default_apk_path} #{renamed_apk_path}")
    puts "Created APK with name: vynthra-#{version_number}.apk"

    # ใช้ Firebase App Distribution กับไฟล์ APK ที่เปลี่ยนชื่อแล้ว
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "internal-testers", # แก้ไขตามต้องการ
      release_notes: "Vynthra version #{version_number}",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      apk_path: renamed_apk_path
    )
  end
end