name: Build and distribute with Fastlane

on:
  push:
    branches:
      - main  # หรือ branch อื่นที่คุณต้องการ

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd android
          bundle install

      - name: Create Firebase Service Credentials file
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" | base64 -d > firebase_credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/firebase_credentials.json" >> $GITHUB_ENV

      - name: Distribute Android app with Fastlane
        run: |
          cd android
          bundle exec fastlane distribute_firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # ถ้าต้องการ build สำหรับ iOS เพิ่มขั้นตอนต่อไปนี้
      # - name: Install CocoaPods
      #   run: |
      #     cd ios
      #     pod install

      # - name: Distribute iOS app with Fastlane
      #   run: |
      #     cd ios
      #     bundle exec fastlane distribute_firebase
      #   env:
      #     FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
